# port of backend
server:
  port: 9090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/servicedatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sqluser
    password: sqlpassword
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

#spring:
#  datasource:
#    url: "jdbc:sqlserver://serviceplatform.database.windows.net:1433;database=servicePlatformData;user=neal@serviceplatform;password=MoreIT-404;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
#    password: MoreIT-404
#    username: neal
#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#    database: sql_server
#  main:
#    allow-circular-references: true


springdoc:
  swagger-ui:
    path: /

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351