# port of backend
server:
  port: 9090
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/servicedatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sqluser
    password: sqlpassword
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql


springdoc:
  swagger-ui:
    path: /

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351